local keymap = vim.api.nvim_set_keymap
keymap('n', '<c-s>', ':w<CR>', {})
keymap('i', '<c-s>', '<Esc>:w<CR>a', {})
local opts = { noremap = true, silent=true }
keymap('n', '<c-j>', '<c-w>j', opts)
keymap('i', '<C-c>', '<Esc>', opts)
keymap('n', '<c-h>', '<c-w>h', opts)
keymap('n', '<c-k>', '<c-w>k', opts)
keymap('n', '<c-l>', '<c-w>l', opts)
keymap('n','gd', ':lua vim.lsp.buf.definition()<cr>',opts)
keymap('n','gD', ':lua vim.lsp.buf.declaration()<cr>',opts)
keymap('n','gi', ':lua vim.lsp.buf.implementation()<cr>',opts)
keymap('n','gw', ':lua vim.lsp.buf.document_symbol()<cr>',opts)
keymap('n','K', ':lua vim.lsp.buf.hover()<cr>',opts)
keymap('n','<leader>rn', ':lua vim.lsp.buf.rename()<cr>',opts)
keymap('n','<c-k>', ':lua vim.lsp.buf.signature_help()<cr>',opts)
keymap('n','<leader>af', ':lua vim.lsp.buf.code_action()<cr>',opts)
keymap("n", "<leader>ff", "<cmd>lua require'telescope.builtin'.find_files(require('telescope.themes').get_ivy({ layout_config = {height = 0.3},previewer = false })) <cr>", opts)
keymap("n", "<leader>dd", "<cmd>lua require'telescope.builtin'.diagnostics(require('telescope.themes').get_ivy({ layout_config = {height = 0.3},previewer = false })) <cr>", opts)
-- keymap("n", "<leader>dd", "<cmd>Telescope diagnostics theme=dropdown<cr>", opts)
keymap("n","<leader>cf",":!clang-format % -i<cr>",opts)
keymap("n","<leader>mk",":make<cr>",opts)
keymap('n','d[', ':lua vim.diagnostic.goto_next()<cr>',opts)
keymap('n','[d', ':lua vim.diagnostic.goto_prev()<cr>',opts)
keymap('n','K', ':lua vim.lsp.buf.hover()<cr>',opts)
keymap('n','<leader>lb', ':set background=light<cr>',opts)
keymap('n','<leader>db', ':set background=dark<cr>',opts)
